### PR TITLE
Incomplete Test: project 1 last step, I made all the code edits. 

### PR DESCRIPTION
**Pull request by jtian98**
Tests all pass as of now, haven't added new tests yet. Edited the format for some files, so it seems like I changed a lot of files... (Just ignore all the indentation changes.)

### CODE REVIEW

**Comment by kevmo314** [comment]
Just curious what did you use to format the code?

**Comment by jtian98** [comment]
@kevmo314 I just did command-A and then command-I in Eclipse since some lines weren't indented, just thought it made the code easier to read.

**Comment by kevmo314** [comment]
Can you try using `google-java-format`? It has an [eclipse plugin](https://github.com/google/google-java-format#eclipse) which should reduce the number of changes. Since different people are using different IDEs I think just using the default formatter will result in a lot of formatting changes back and forth so it would be good to standardize on a tool.

**Comment by jtian98** [comment]
@kevmo314 For sure! Sorry I assumed everyone was using eclipse and just manually indenting which resulted in non-standardized formatting. I'll try using the tool you mentioned!

**Pull request merged**
